### ISSUE TITLE
Shell not working

### ISSUE THREAD

**Issue by Domse007** [HubDanDevMan/matura#1]
I'm trying to run the shell, but unfortunately, it doesn't compile for me.

`IF=shell make`

`nasm -fbin -w+all -O1 -p firststage.asm shell/shell.asm -o shell.bin
keyboard/keyboard.asm:38: warning: unterminated string [-w+other]
shell/shell.asm:8: warning: unterminated string [-w+other]
shell/shell.asm:225: error: end of file while still defining macro ShellCmp'
make: *** [Makefile:41: default] Error 1`

**Comment by TheArchitectOfTheBlessedMachine** [comment]
Should be fixed now.
